### ISSUE TITLE
FlamePaper 1.8 - ArmorStand

### ISSUE THREAD

**Issue by SiriHackYT** [2lstudios-mc/FlamePaper#14]
I have an issue with entity Armorstand, when i want to spawn a armorstand with my spigot plugin, this doesn't work, but with paper or spigot all it's work :/

I have no error in the console

**Comment by xIsm4** [comment]
Then it only work on Spigot i guess? Not a FlamePaper problem.

**Comment by linsaftw** [comment]
> I have an issue with entity Armorstand, when i want to spawn a armorstand with my spigot plugin, this doesn't work, but with paper or spigot all it's work :/
> 
> I have no error in the console

Hello, can you try latest github release? Thanks!

**Comment by linsaftw** [comment]
Closed because of no response
