### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by vLuckyyy** [2lstudios-mc/FlamePaper#21]
Hi, could you please add support for new java versions?

**Comment by TheJoshue** [comment]
there is no need to
why?
use java8 for 1.8-1.11, always, it's the best because java8 and mc 1.8 are released near between their times of release

**Comment by andreasdc** [comment]
> there is no need to why? use java8 for 1.8-1.11, always, it's the best because java8 and mc 1.8 are released near between their times of release

Why don't you use old log4j version too?

**Comment by TheJoshue** [comment]
> > there is no need to why? use java8 for 1.8-1.11, always, it's the best because java8 and mc 1.8 are released near between their times of release
> 
> Why don't you use old log4j version too?

go ahead run any fork of 1.8 compiled with java17 and send us your logs file

**Comment by andreasdc** [comment]
> > > there is no need to why? use java8 for 1.8-1.11, always, it's the best because java8 and mc 1.8 are released near between their times of release
> > 
> > 
> > Why don't you use old log4j version too?
> 
> go ahead run any fork of 1.8 compiled with java17 and send us your logs file

I'm already doing that, stay on Java 8 or even downgrade. hehe

**Comment by TheJoshue** [comment]
it's up to you what you'll do, patch plugins to work on mc1.8 with java >8 and it's ok
when you want to add some plugins and they suddenly don't work you'll need to patch them too - too much work
either be smart or work hard, what else to say

**Comment by vLuckyyy** [comment]
Java 17 is the future.

**Comment by LewUwU** [comment]
> Java 17 is the future.

Yes

**Comment by vLuckyyy** [comment]
Sitting on old java versions is weak, better to switch to new java versions, for example my whole server is on the latest java
