### ISSUE TITLE
Connection Handler

### ISSUE THREAD

**Issue by seogwam** [2lstudios-mc/FlamePaper#24]
If a player enters the server, there will be a delay.

Minecraft::Connection Handlercount(1)  total(99.64% 0.072s, 143.42% of tick)avg(71.71ms per - 71.71ms/1.00 per tick)

this is my server timngs
[https://timings.aikar.co/?id=946cd7fb8c8140ebbbaf63bca3722783](url)

I'm using the flame cord, too.

Is there a way to solve the problem? 👍

**Comment by linsaftw** [comment]
This doesn't have to do with FlamePaper itself, but with the connection of your machine. Make sure compression-threshold is at it's default value and that you have your linux machine updated and sub-servers recommended to be on localhost.
