### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by craciu25yt** [2lstudios-mc/FlamePaper#25]
Estaba usando paper y pues cambie a flamepaper. Y bueno pues paso esto XD 
![image](https://user-images.githubusercontent.com/48807342/151199615-983ac916-b86e-421d-ae42-00035b69daa2.png)

**Comment by andreasdc** [comment]
> Estaba usando paper y pues cambie a flamepaper. Y bueno pues paso esto XD

iċċekkja l-plugins tiegħek

**Comment by craciu25yt** [comment]
> 

um what?

**Comment by xIsm4** [comment]
> Estaba usando paper y pues cambie a flamepaper. Y bueno pues paso esto XD ![image](https://user-images.githubusercontent.com/48807342/151199615-983ac916-b86e-421d-ae42-00035b69daa2.png)

No veo nada ahí, simplemente no hay ningún plugin o no esta funcionando vería bien cerra el issue-post.

**Comment by linsaftw** [comment]
No veo el error.
