### ISSUE TITLE
Algunos plugins no funcionan

### ISSUE THREAD

**Issue by craciu25yt** [2lstudios-mc/FlamePaper#26]
al usar flamepaper plugins como Console Spam Fix deja de funcionar. Despues bedwars 1058 dice 

BedWars1058 may drop support for this server version in the future.
Please consider upgrading to a newer paper/spigot version. 

cuando con paper no me decia eso

**Comment by xIsm4** [comment]
> al usar flamepaper plugins como Console Spam Fix deja de funcionar. Despues bedwars 1058 dice
> 
> BedWars1058 may drop support for this server version in the future. Please consider upgrading to a newer paper/spigot version.
> 
> cuando con paper no me decia eso

El consoleSpamFix es una perdida de tiempo, y no arregla nada solo hace que no veas los problemas que tiene tu servidor y no arreglarlos terminara en peores cosas.
Y ese mensaje de Bedwars1058 solo dice que probablemente deje de soportar 1.8.9 (Cosa que tu estas usando por que TU quieres)

**Comment by linsaftw** [comment]
Buenas, prueba la ultima version. https://github.com/2lstudios-mc/FlamePaper/releases/tag/7619580

**Comment by craciu25yt** [comment]
Isma a mi eso no me pasa con 1.8 de paper y eso no se actualiza de hace mucho tiempo

**Comment by craciu25yt** [comment]
Ahora cuando pueda pruebo linsa

**Comment by linsaftw** [comment]
Voy a cerrar el issue ya que no se recibio mas info. Lo del bedwars ni idea porque sera.
