### ISSUE TITLE
Pom.xml dependencies repo url changed.

### ISSUE THREAD

**Issue by PermisosDev** [2lstudios-mc/FlamePaper#3]
`https://repo.destroystokyo.com/content/repositories/releases/` changed to `https://papermc.io/repo/repository/maven-releases/`

Change this:
https://github.com/2LStudios-MC/FlamePaper/blob/e3102aa9fd758c7d316cd371b3dc8eae9f056d62/pom.xml#L40
To This:
https://github.com/PaperMC/Paper/blob/89be8185dbe966059997bd104f572738c92bc1ba/pom.xml#L48

**Comment by linsaftw** [comment]
Please make a PR and i will merge it.
