### ISSUE TITLE
not able to compile 

### ISSUE THREAD

**Issue by ProtoGhost** [2lstudios-mc/FlamePaper#30]
Apache Maven 3.8.4
openjdk version "1.8.0_322

[error.txt](https://github.com/2lstudios-mc/FlameCord/files/8373838/error.txt)
please help me

**Comment by xIsm4** [comment]
> Apache Maven 3.8.4 openjdk version "1.8.0_322
> 
> [error.txt](https://github.com/2lstudios-mc/FlameCord/files/8373838/error.txt) please help me

Try on linux

**Comment by madmobhunter** [comment]
I get the same error on widows. could you please post a release of the current build. there are no builds up at the moment for FlamePaper or FlameCord.

**Comment by linsaftw** [comment]
It only works on linux at the moment and I have no experience with this kind of repositories.
