### ISSUE TITLE
SlimeWorldManager Incompatibility when trying to restore a map with Marcely's Bedwars

### ISSUE THREAD

**Issue by pabloalba16** [2lstudios-mc/FlamePaper#36]
![unknown (1)](https://user-images.githubusercontent.com/49927979/189481378-d2be2290-a3d9-4135-bf68-134b4c869192.png)

In order to restore the map, it shows this error showing the incompatibility, Making impossible to rstore the arena in order to play again in it. Using the latest SlimeWorldManager version for 1.8.8 which is 2.2.1. Tested with regular paper and no issues or incompatibilities found

**Comment by pabloalba16** [comment]
Lo he escrito en ingles pero podemos hablar en español si quieres

**Comment by xIsm4** [comment]
> ![unknown (1)](https://user-images.githubusercontent.com/49927979/189481378-d2be2290-a3d9-4135-bf68-134b4c869192.png)
> 
> In order to restore the map, it shows this error showing the incompatibility, Making impossible to rstore the arena in order to play again in it. Using the latest SlimeWorldManager version for 1.8.8 which is 2.2.1. Tested with regular paper and no issues or incompatibilities found

Me parece que es un problema con el parche que modifica FlamePaper para hacer los chunks configurables.

**Comment by pabloalba16** [comment]
Puede ser y es un cambio que muchos forks tienen. Parece que los forks no quieren dar soporte a SWM pero a mi me permite regenerar arenas instantaneamente sin impacto en el rendimiento. Por eso espero que Linsa me haga caso y le de compatibilidad, es de los pocos forks que he visto que no tienen problemas de compatibilidad con practicamente ningun plugin

**Comment by linsaftw** [comment]
Seria genial dar soporte a SWM pero si eso implica incrementar el uso de ram en usos cotidianos no se si sea buena idea aun asi se vera de que forma puede hacerse compatible sin perder el parche.

**Comment by pabloalba16** [comment]
Gracias Linsa!

**Comment by linsaftw** [comment]
Solved in [325b2f6](https://github.com/2lstudios-mc/FlamePaper/commit/325b2f68a0c0aa695d3e9725aeda171c1199ba19)
