### ISSUE TITLE
Java 11 Support

### ISSUE THREAD

**Issue by LautaKooh** [2lstudios-mc/FlamePaper#37]
https://pastebin.com/NhWiKkGi

**Comment by linsaftw** [comment]
FlamePaper does not support being run with Java 11 but it would be a good idea to make it work.

**Comment by linsaftw** [comment]
solved in [c9a90c1](https://github.com/2lstudios-mc/FlamePaper/commit/c9a90c1a3889c995c12f96ac96419cd041cf0ae9)
