### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by beautybloodtr** [2lstudios-mc/FlamePaper#38]
**My suggestions:**

- Spawner Tick Rate Feature (with example)
```
  min-spawn-delay: 600
  max-spawn-delay: 1000
```
- Spawner Particles opinion
- MobAI (with world select options)
- Thread Affinity
- Highly hopper push based feature
- Mob Stack (i guess if this features in spigot thats will optimization better than plugins)
- Knockback system
- Durability control system
- Disable craftings system
- /fps (command for disable some particles, falling blocks, tnts, pistons)
- Armor Stand optimizations
- Redstone fire BlockPhysicsEvent
- Hoppers fire InventoryMoveItemEvent

**Comment by linsaftw** [comment]
Most of this patches are already implemented and others have no explanation at all.
