### ISSUE TITLE
The problem with "new java"

### ISSUE THREAD

**Issue by MisterLolxd2** [2lstudios-mc/FlamePaper#41]
FlamePaper ver: "[FlamePaper - Update 325b2f6](https://builtbybit.com/resources/flamepaper-fix-performance-security.19660/update/91281/)
Java: 17 in 8 is the same problem.
I use BungeeCord
Problem: From the day of the update on my server there is a problem that spams such warnings etc. I do not know what it depends on, some users normally disconnect, and others leave such spam. It would not bother me especially if it were not for the fact that the last "spam" crashed my server...
I send logs in this way, because they weigh too much. https://www.mediafire.com/file/4uaz2yihcj2zon4/logs.txt/file
Sorry for my english ^_^.

**Comment by linsaftw** [comment]
Fixed in latest. Soon on MC-Market.
