### ISSUE TITLE
Factions Features

### ISSUE THREAD

**Issue by Jimaras951** [2lstudios-mc/FlamePaper#47]
Sorry if not the right section to post but im confused with github sorry.

My suggestion except of improving server protection which is already being perfect. i see that it can be used in multiple server mode such as prison skyblock hubs etc but not in factions because of not being improved on some sections that if possible should be improved to fullfill the fork. 

some features that should be on the fork in case of being improved as a fork for factions.
those features are from an old abadoned fork. the forks that are currently available for a faction server are less than 3 probably

cannon performance improvement
Option to disable left shooting
Fix blocks which break falling sand
Obsidian Destroyer
Sand optimization
Built in live tps graph /tps
View recommended configs in order to enhance cannoning and overall server performance
Chunk mob limiter
/tnttoggle and /sandtoggle for hiding sand and tnt entities
Disable roof cannons
Limit tnt and sand packets

thanks for considering.

**Comment by linsaftw** [comment]
Done improvements for cannon performance. Any other features should be asked separatedly.
