### ISSUE TITLE
TPS Drop Problem / FlamePaper

### ISSUE THREAD

**Issue by CemBe1** [2lstudios-mc/FlamePaper#48]
Hi,there is no plugin in the server.
TPS drops are happening. 

My timings: https://timings.aikar.co/dev/?id=9ec899d1495240c59261420198198fee

**Comment by LewUwU** [comment]
Does this happen with default PaperSpigot?

**Comment by linsaftw** [comment]
This is probably related to chunk unload and the memory leak fix patch.

**Comment by linsaftw** [comment]
Please send spark logs so we can find the cause more accurately.

**Comment by linsaftw** [comment]
Last patches will probably fix the issue.
