### ISSUE TITLE
 ProtocolLib 4.6.0 does not work on FlamePaper.

### ISSUE THREAD

**Issue by Regomy** [2lstudios-mc/FlamePaper#50]
FlamePaper: latest
protocollib: 4.6.0
logs:
  Error aac+protocollib 4.8.0 (no FlamePaper error)
  https://paste.md-5.net/ufarohuriy.cs

Error flamepaper and protocollib 4.6.0
https://paste.md-5.net/utarayihuk.cpp

**Comment by linsaftw** [comment]
Can you try 4.7.0? https://www.spigotmc.org/resources/protocollib.1997/download?version=408253

**Comment by linsaftw** [comment]
Probably new FlamePaper version will fix it. Coming soon!

**Comment by linsaftw** [comment]
Can't fix due to ProtocolLib 3.6 not supporting Netty newest versions which means reverting Java 19 support and dropping library updates which will decrease performance and stability.
