### ISSUE TITLE
0039-Disable-Idle-Player-Position-Updates.patch

### ISSUE THREAD

**Issue by iSilviu-debug** [2lstudios-mc/FlamePaper#56]
https://github.com/2lstudios-mc/FlamePaper/blob/7f37d4ab7801029ed42d35a98e5cef28a3fdcac3/PaperSpigot-Server-Patches/0039-Disable-Idle-Player-Position-Updates.patch#L16

I have a question: does it work?

If you notice, the '`from`' variable will almost always be different:
https://github.com/2lstudios-mc/FlamePaper/blob/7f37d4ab7801029ed42d35a98e5cef28a3fdcac3/PaperSpigot-Server-Patches/0039-Disable-Idle-Player-Position-Updates.patch#L20
This other patch prevents the `lastPosX, lastPosY, lastPosZ, lastYaw, lastPitch` from being changed continuously, whereas you will in fact notice that the position `to` will change continuously.

**Comment by linsaftw** [comment]
Players send position packets when they stay on ground. This patch ignores this packets. The other one just avoids "updating" when only the decimals change but still receives the packet and processes it.
