### ISSUE TITLE
remove unloaded not works with multiverse-core 

### ISSUE THREAD

**Issue by F3F5** [2lstudios-mc/FlamePaper#59]
FlamePaper 1.8.8 remove-unloaded:
      enderpearls: true
      tnt-entities: true
      falling-blocks: true   I think this patch doesn't work with multiverse core. At the end of the duel, when fireworks are flying, if you throw pearls, then the next time you play on this map, you'll get teleported to place where the pearls were supposed to land.

**Comment by linsaftw** [comment]
Because chunks are not unloaded as soon as you leave, but after some seconds of inactivity.

**Comment by F3F5** [comment]
> Because chunks are not unloaded as soon as you leave, but after some seconds of inactivity. What you want is to prevent pearl teleports to other worlds.

maybe this caused by GrimAC by worldsync check, so i check this.
