### ISSUE TITLE
Error to Compile

### ISSUE THREAD

**Issue by HanielCota** [2lstudios-mc/FlamePaper#60]
The MD5 checksum of the downloaded server jar does not match the BuildData hash.

**Comment by linsaftw** [comment]
Can't replicate.

**Comment by HanielCota** [comment]
I went to build the src to generate the plugin using bash and I got this error

**Comment by linsaftw** [comment]
If you bought the project I can assist you with compiling via Discord. No compiling support for non-buyers.
