### ISSUE TITLE
Removing CancelledPacketHandleException

### ISSUE THREAD

**Issue by Mercenarioo** [2lstudios-mc/FlamePaper#61]
Is CancelledPacketHandleException needed? Doesn't throwing the exception on every incoming packet cause performance problems? Thanks for answer!

**Comment by linsaftw** [comment]
This is only thrown on specific cases, which means it wont use up performance. Right?

**Comment by Mercenarioo** [comment]
It's being thrown for every incoming packet, because of poor packet system, unfortunately.

**Comment by linsaftw** [comment]
> It's being thrown for every incoming packet, because of poor packet system, unfortunately.

What are the lines of code involved on this?

**Comment by Mercenarioo** [comment]
In NetworkManager and in PlayerConnectionUtils, I tried to removed it, but it caused some errors with refCnt or something.

**Comment by linsaftw** [comment]
> In NetworkManager and in PlayerConnectionUtils, I tried to removed it, but it caused some errors with refCnt or something.

That probably means its not possible...

**Comment by Mercenarioo** [comment]
But almost everything worked normally, it would need some changes to the packet system, maybe something like Velocity.
