### ISSUE TITLE
BUG sitting in the carriage will leave the game

### ISSUE THREAD

**Issue by Regomy** [2lstudios-mc/FlamePaper#62]
Hello, noticed a bug, if a player sitting in the carriage will leave the game, then it will warm in a carriage, although there is a plugin to spawn, and without the carriage teleports him to the spawn. By the way, when you leave, the wagon disappears with the player.

**Comment by linsaftw** [comment]
Maybe the plugin to spawn has to check this.

**Comment by Regomy** [comment]
@linsaftw when exiting the wagon disappears with the player! This plugin can't check for spawns :/

**Comment by linsaftw** [comment]
> @linsaftw when exiting the wagon disappears with the player! This plugin can't check for spawns :/

So you want to unride when leaving the server?

**Comment by Regomy** [comment]
> 

@linsaftw this is bug! Carriage just disappear with the player on exit, and it should be so that if the player went out, the other could sit in the wagon, and when entering. Let them appear next to the wagonette. This is a bug, it's not the plugin's fault.

**Comment by linsaftw** [comment]
So, you want to unride upon quit?

**Comment by Regomy** [comment]
> So, you want to unride upon quit?

If a player leaves the server while sitting in a wagon, the wagon disappears with him. And the .teleport does not drop the player if he is sitting in the wagonette. I WANT THE WAGONETTE TO NOT DISAPPEAR ON EXIT!

**Comment by linsaftw** [comment]
Okay, solution would be to unride upon exit then. I will see if it's possible.

**Comment by Regomy** [comment]
> Okay, solution would be to unride upon exit then. I will see if it's possible.

I would be very grateful!
