### ISSUE TITLE
enderpearl flag block

### ISSUE THREAD

**Issue by Regomy** [2lstudios-mc/FlamePaper#63]
Players who throw ender pearl at blocks can get stuck in them, and players who throw at glass panels can go through them. Please fix this, so that the ender perl does not let through the panels, and does not allow to get stuck in the blocks. @F3F5 https://github.com/F3F5/EnderPearlFix/tree/main/src/main/java/f3f5/enderpearlfix has a solution for getting stuck in blocks, but no solution for teleportation through glass panels if you throw 2 ender pearls at a time. Please fix both problems.

**Comment by F3F5** [comment]
xd

**Comment by linsaftw** [comment]
Not as easy as you mention. Add cooldown to pearls.
