### ISSUE TITLE
Don't load chunks on portal exit

### ISSUE THREAD

**Issue by F3F5** [2lstudios-mc/FlamePaper#65]
best patch for low hp hostings. https://github.com/ruViolence/Reaper/commit/559060403bb7eeea25c889abb1723ef485a27ba2,

 it save's my tps a lot. without this patch i have 10 tps, patch-18-20 tps. **but in patch bug:  throw entity into an unloaded chunk of the portal, then they are in another world not where they should be, but fall from the sky**

**Comment by andreasdc** [comment]
How does that fix anything?

**Comment by F3F5** [comment]
> How does that fix anything?

generates chunks after teleportation

**Comment by andreasdc** [comment]
> > How does that fix anything?
> 
> generates chunks after teleportation

I think it just blocks generating chunks when searching for portal.

**Comment by F3F5** [comment]
@linsaftw in this patch 1 bug. if i drop any item it can be wrong location in world (because is is not loaded)

**Comment by F3F5** [comment]
you fixed this?

**Comment by linsaftw** [comment]
> you fixed this?

No way to fix. What other solution do you have?

**Comment by F3F5** [comment]
> > you fixed this?
> 
> No way to fix. What other solution do you have?

no.

**Comment by F3F5** [comment]
maybe make for default to false ? @linsaftw

**Comment by linsaftw** [comment]
We will have to remove this patch.
